# Rust formatting configuration (stable features only)
edition = "2024"

# Indentation and spacing
max_width = 100
hard_tabs = false
tab_spaces = 4

# Imports
reorder_imports = true

# Use field init shorthand
use_field_init_shorthand = true

# Function calls
use_small_heuristics = "Max"

# Match arms
match_block_trailing_comma = true

# Misc formatting
use_try_shorthand = true

# Chain formatting
chain_width = 60
single_line_if_else_max_width = 50

# Newlines
newline_style = "Unix"
