name: CI

on:
  push:
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v27
      - name: Install, lint, test
        run: nix-shell --run "bash -lc \"bun install --frozen-lockfile && bun run build && bun run lint && bun run test\""
